// Describing the different ACTION NAMES available
export const LOAD_BEERS_REQUESTED = "LOAD_BEERS_REQUESTED";
export const LOAD_BEERS_SUCCEEDED = "LOAD_BEERS_SUCCEEDED";
export const LOAD_NEW_PAGE = "LOAD_NEW_PAGE";
export const CHANGE_MIN_FIRST_BREWED_FILTER = "CHANGE_MIN_FIRST_BREWED_FILTER";
export const CHANGE_MAX_FIRST_BREWED_FILTER = "CHANGE_MAX_FIRST_BREWED_FILTER";
